In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style

In [2]:
style.use('ggplot')

In [3]:
%matplotlib inline

In [5]:
dfDaa = pd.read_csv('train_unhashed_examples.csv')

In [6]:
dfDaa.head()

,id,dt_prediction_date,dt_target_date,s_model_type,cat_case_type,cat_s_flightno,dt_flight_date,num_flight_year,num_flight_month,num_flight_weekofyear,...,num_pax_105_119_mins_before_sdt,num_pax_120_134_mins_before_sdt,num_pax_135_149_mins_before_sdt,num_pax_150_164_mins_before_sdt,num_pax_165_179_mins_before_sdt,num_pax_180_194_mins_before_sdt,num_pax_195_209_mins_before_sdt,num_pax_210_224_mins_before_sdt,num_pax_225_239_mins_before_sdt,num_pax_240plus_mins_before_sdt
0,14039,31-May-12,31-May-13,52_weeks,Target,EI698,31-May-13,2013,5,22,...,6,8,4,1,6,0,10,3,8,7
1,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,31-May-12,2012,5,22,...,8,5,0,10,3,8,2,0,6,5
2,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,30-May-12,2012,5,22,...,0,9,2,1,10,3,4,6,6,4
3,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,29-May-12,2012,5,22,...,2,8,6,9,3,1,6,7,8,6
4,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,28-May-12,2012,5,22,...,3,9,4,6,4,6,9,3,9,7

In [8]:
dfDaa.columns

Index(['id', 'dt_prediction_date', 'dt_target_date', 's_model_type',
       'cat_case_type', 'cat_s_flightno', 'dt_flight_date', 'num_flight_year',
       'num_flight_month', 'num_flight_weekofyear', 'num_flight_dayofweek',
       'cat_sdt_hour', 'cat_s_airport_desc', 'cat_s_city_desc',
       'cat_destination_group_id', 'cat_longhaul_ind', 'num_airport_other_ops',
       'num_airport_other_flights', 'num_city_other_ops',
       'num_city_other_flights', 'cat_s_plane_capacity',
       'cat_flight_class_type_id', 'ord_leisure', 'ord_irish_residents',
       'ord_trip_duration', 'ord_female', 'ord_party_size', 'ord_bag_checkin',
       'ord_arrive_by_car', 'num_pax_000_014_mins_before_sdt',
       'num_pax_015_029_mins_before_sdt', 'num_pax_030_044_mins_before_sdt',
       'num_pax_045_059_mins_before_sdt', 'num_pax_060_074_mins_before_sdt',
       'num_pax_075_089_mins_before_sdt', 'num_pax_090_104_mins_before_sdt',
       'num_pax_105_119_mins_before_sdt', 'num_pax_120_134_mins_before_sdt',
       'num_pax_135_149_mins_before_sdt', 'num_pax_150_164_mins_before_sdt',
       'num_pax_165_179_mins_before_sdt', 'num_pax_180_194_mins_before_sdt',
       'num_pax_195_209_mins_before_sdt', 'num_pax_210_224_mins_before_sdt',
       'num_pax_225_239_mins_before_sdt', 'num_pax_240plus_mins_before_sdt'],
      dtype='object')

In [10]:
dfDaa.ord_leisure

0     2
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    3
21    3
22    3
Name: ord_leisure, dtype: int64

In [11]:
dfDaa.dt_prediction_date.value_counts()

31-May-12    13
15-Oct-13    10
Name: dt_prediction_date, dtype: int64

In [12]:
dfDaa.dt_flight_date.value_counts()

28-May-12    1
18-Sep-13    1
15-Oct-13    1
02-Dec-11    1
11-May-12    1
31-May-13    1
15-Oct-14    1
27-May-12    1
25-Sep-13    1
10-Oct-13    1
26-May-12    1
06-Apr-12    1
25-May-12    1
02-Mar-12    1
12-Oct-13    1
02-Oct-13    1
09-Oct-13    1
13-Oct-13    1
30-May-12    1
04-May-12    1
29-May-12    1
31-May-12    1
14-Oct-13    1
Name: dt_flight_date, dtype: int64

In [13]:
dfDaa.dt_target_date.value_counts()

31-May-13    13
15-Oct-14    10
Name: dt_target_date, dtype: int64

In [14]:
dfDaa.cat_case_type.value_counts()

Expl      21
Target     2
Name: cat_case_type, dtype: int64

In [17]:
dfDaa[dfDaa.cat_case_type == 'Target']

,id,dt_prediction_date,dt_target_date,s_model_type,cat_case_type,cat_s_flightno,dt_flight_date,num_flight_year,num_flight_month,num_flight_weekofyear,...,num_pax_105_119_mins_before_sdt,num_pax_120_134_mins_before_sdt,num_pax_135_149_mins_before_sdt,num_pax_150_164_mins_before_sdt,num_pax_165_179_mins_before_sdt,num_pax_180_194_mins_before_sdt,num_pax_195_209_mins_before_sdt,num_pax_210_224_mins_before_sdt,num_pax_225_239_mins_before_sdt,num_pax_240plus_mins_before_sdt
0,14039,31-May-12,31-May-13,52_weeks,Target,EI698,31-May-13,2013,5,22,...,6,8,4,1,6,0,10,3,8,7
13,10566,15-Oct-13,15-Oct-14,52_weeks,Target,UA022,15-Oct-14,2014,10,42,...,4,2,9,6,8,6,0,4,7,4

In [18]:
dfDaa[dfDaa.cat_case_type == 'Expl']

,id,dt_prediction_date,dt_target_date,s_model_type,cat_case_type,cat_s_flightno,dt_flight_date,num_flight_year,num_flight_month,num_flight_weekofyear,...,num_pax_105_119_mins_before_sdt,num_pax_120_134_mins_before_sdt,num_pax_135_149_mins_before_sdt,num_pax_150_164_mins_before_sdt,num_pax_165_179_mins_before_sdt,num_pax_180_194_mins_before_sdt,num_pax_195_209_mins_before_sdt,num_pax_210_224_mins_before_sdt,num_pax_225_239_mins_before_sdt,num_pax_240plus_mins_before_sdt
1,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,31-May-12,2012,5,22,...,8,5,0,10,3,8,2,0,6,5
2,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,30-May-12,2012,5,22,...,0,9,2,1,10,3,4,6,6,4
3,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,29-May-12,2012,5,22,...,2,8,6,9,3,1,6,7,8,6
4,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,28-May-12,2012,5,22,...,3,9,4,6,4,6,9,3,9,7
5,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,27-May-12,2012,5,22,...,9,7,4,2,0,6,8,3,5,4
6,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,26-May-12,2012,5,21,...,0,2,3,7,2,2,1,2,6,3
7,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,25-May-12,2012,5,21,...,10,1,5,6,1,9,5,5,0,8
8,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,11-May-12,2012,5,19,...,7,7,7,6,7,8,0,10,0,0
9,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,04-May-12,2012,5,18,...,5,2,0,1,0,3,8,3,10,7
10,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,06-Apr-12,2012,4,14,...,0,1,5,3,4,8,4,3,0,4
11,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,02-Mar-12,2012,3,9,...,9,0,1,4,10,1,8,2,1,9
12,14039,31-May-12,31-May-13,52_weeks,Expl,EI698,02-Dec-11,2011,12,49,...,5,4,3,7,2,10,0,1,1,10
14,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,15-Oct-13,2013,10,42,...,1,3,10,5,6,8,8,8,0,8
15,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,14-Oct-13,2013,10,42,...,9,5,5,5,5,10,8,10,5,8
16,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,13-Oct-13,2013,10,42,...,3,1,9,2,9,4,6,3,4,2
17,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,12-Oct-13,2013,10,41,...,8,10,7,7,9,4,2,2,1,1
18,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,10-Oct-13,2013,10,41,...,5,4,4,9,2,6,4,10,0,10
19,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,09-Oct-13,2013,10,41,...,9,8,7,10,3,2,6,10,6,3
20,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,02-Oct-13,2013,10,40,...,4,1,3,10,10,5,5,7,0,6
21,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,25-Sep-13,2013,9,39,...,9,9,6,4,7,9,0,8,8,7
22,10566,15-Oct-13,15-Oct-14,52_weeks,Expl,UA022,18-Sep-13,2013,9,38,...,9,7,4,8,7,3,6,8,3,7